export default {
  BITCOIN_NETWORK : 'testnet',
  ETHEREUM_NETWORK : 'ropsten',
  INFURA_API_KEY: 'qMZ7EIind33NY9Azu836',
  BACKUP: 'Backup',
  RECEIVE: 'Receive',
  RECEIVED: 'Received',
  SEND: 'Send',
  SENT: 'Sent',
  ADD_NEW_WALLET: 'Add new wallet',
  SCAN_QR_CODE: 'Scan QR Code',
  COPY: 'Copy',
  SHARE: 'Share',
  TRANSACTIONS: 'Transactions',
  TOKEN: 'Token',
  ETHEREUM: 'Ethereum',
  PENDING: 'Pending',
  SELF: 'Self',
  
}